var yeoman   = require('yeoman-generator'),
    util     = require('util'),
    YPConfig = require('../../node_modules/generator-wordpress/util/config');

// Export the module
module.exports = Generator;

// Extend the base generator
function Generator(args, options, config) {
	yeoman.generators.Base.apply(this, arguments);

  this.option('skip-yp');

	this.YPConf = new YPConfig();
}
util.inherits(Generator, yeoman.generators.Base);

Generator.prototype.fireItUp = function() {

	if(this.options.skipYp) {
		//TODO: Check if YeoPress has already been initalised and 
		//throw error if not
		return;
	}

	this.composeWith('wordpress', {}, {
	  local: require.resolve('generator-wordpress')
	});
};

Generator.prototype.turnUpTheConfigHeat = function() {
	
	var done = this.async();

	/*
	 * HACK Warning. we commit the filesystem before and after deleting
	 * the wp-config.php generated by YeoPress in order to avoid YeoMan asking
	 * if we are sure we'd like to overwrite the file
	 */
	this.fs.delete(this.destinationPath('wp-config.php'));
	this.fs.delete(this.destinationPath('local-config.php'));
	this.fs.delete(this.destinationPath('.gitignore'));
	this.fs.commit(done);

	this.template('wp-config.php.tmpl', 'wp-config.php');
	this.template('wp-config-local.php.tmpl', 'wp-config-local.php');
	this.template('gitignore.tmpl', '.gitignore');
};